-- MySQL Script generated by MySQL Workbench
-- Thu Jun  7 16:55:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fiche_de_prise_en_charge_materiel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fiche_de_prise_en_charge_materiel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiche_de_prise_en_charge_materiel` DEFAULT CHARACTER SET utf8 ;
USE `fiche_de_prise_en_charge_materiel` ;

-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`villes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`villes` (
  `id` VARCHAR(45) NOT NULL COMMENT 'nom de la ville',
  `code_postale` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`clients` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `rue` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telephone_fixe` VARCHAR(10) NULL,
  `telephone_portable` VARCHAR(10) NULL,
  `ville_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ville_idx` (`ville_id` ASC),
  CONSTRAINT `ville`
    FOREIGN KEY (`ville_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`villes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`produits` (
  `id` INT NOT NULL,
  `lien_photo` VARCHAR(45) NULL,
  `OS` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_idx` (`client_id` ASC),
  CONSTRAINT `client`
    FOREIGN KEY (`client_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`utilisateurs` (
  `id_utilisateur` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `telephone_fixe` VARCHAR(10) NULL,
  `telephone_portable` VARCHAR(10) NULL,
  `mdp` VARCHAR(45) NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`fiches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`fiches` (
  `id` INT NOT NULL,
  `date_debut` DATE NULL,
  `date_fin` DATE NULL,
  `prix` INT NULL,
  `utilisateur_id` VARCHAR(45) NOT NULL,
  `produit_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `utilisateur_idx` (`utilisateur_id` ASC),
  INDEX `fk_fiches_produits1_idx` (`produit_id` ASC),
  INDEX `fk_fiches_clients1_idx` (`client_id` ASC),
  CONSTRAINT `utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiches_produits1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiches_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`problemes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`problemes` (
  `id` VARCHAR(100) NOT NULL COMMENT 'description du problème',
  `prix_resolution` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`services_qualites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`services_qualites` (
  `id` VARCHAR(45) NOT NULL COMMENT 'nom du services',
  `observation` VARCHAR(45) NULL,
  `ok` TINYINT NULL,
  `ko` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`materiels_externes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`materiels_externes` (
  `id` INT NOT NULL,
  `etat` VARCHAR(45) NULL,
  `produit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `produit_idx` (`produit_id` ASC),
  CONSTRAINT `produit`
    FOREIGN KEY (`produit_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`donnees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`donnees` (
  `id` INT NOT NULL,
  `importance` VARCHAR(45) NULL,
  `produit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_donnees_produits1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_donnees_produits1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`pieces_detachees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`pieces_detachees` (
  `id` INT NOT NULL,
  `prix` VARCHAR(45) NULL,
  `etat` VARCHAR(45) NULL,
  `produit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pieces_detachees_produits1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_pieces_detachees_produits1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`produit_a_problemes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`produit_a_problemes` (
  `probleme_id` VARCHAR(100) NOT NULL,
  `produit_id` INT NOT NULL,
  INDEX `fk_produit_a_problemes_problemes1_idx` (`probleme_id` ASC),
  INDEX `fk_produit_a_problemes_produits1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_produit_a_problemes_problemes1`
    FOREIGN KEY (`probleme_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`problemes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_a_problemes_produits1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiche_de_prise_en_charge_materiel`.`services_recus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiche_de_prise_en_charge_materiel`.`services_recus` (
  `produit_id` INT NOT NULL,
  `service_qualite_id` VARCHAR(45) NOT NULL,
  INDEX `fk_services_recus_produits1_idx` (`produit_id` ASC),
  INDEX `fk_services_recus_services_qualites1_idx` (`service_qualite_id` ASC),
  CONSTRAINT `fk_services_recus_produits1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_services_recus_services_qualites1`
    FOREIGN KEY (`service_qualite_id`)
    REFERENCES `fiche_de_prise_en_charge_materiel`.`services_qualites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
